[2024-11-09T22:39:55.909+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/test.py
[2024-11-09T22:39:55.910+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:39:55.912+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:39:55.912+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:39:55.954+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:39:55.944+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:39:55.957+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:39:55.975+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.069 seconds
[2024-11-09T22:40:26.324+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/test.py
[2024-11-09T22:40:26.325+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:40:26.327+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:40:26.326+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:40:26.336+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:40:26.334+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:40:26.337+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:40:26.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.039 seconds
[2024-11-09T22:40:56.781+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/test.py
[2024-11-09T22:40:56.782+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:40:56.784+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:40:56.784+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:40:56.792+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:40:56.790+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:40:56.793+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:40:56.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.029 seconds
[2024-11-09T22:41:27.229+0000] {processor.py:157} INFO - Started process (PID=198) to work on /opt/airflow/dags/test.py
[2024-11-09T22:41:27.230+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:41:27.232+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:41:27.232+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:41:27.243+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:41:27.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:41:27.244+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:41:27.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-11-09T22:41:57.676+0000] {processor.py:157} INFO - Started process (PID=203) to work on /opt/airflow/dags/test.py
[2024-11-09T22:41:57.677+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:41:57.678+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:41:57.678+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:41:57.687+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:41:57.685+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:41:57.687+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:41:57.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.034 seconds
[2024-11-09T22:42:28.136+0000] {processor.py:157} INFO - Started process (PID=208) to work on /opt/airflow/dags/test.py
[2024-11-09T22:42:28.137+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:42:28.138+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:42:28.138+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:42:28.146+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:42:28.144+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:42:28.146+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:42:28.167+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.034 seconds
[2024-11-09T22:44:41.050+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/test.py
[2024-11-09T22:44:41.051+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:44:41.052+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:44:41.052+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:44:41.155+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:44:41.150+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:44:41.156+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:44:41.173+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.125 seconds
[2024-11-09T22:45:11.410+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/test.py
[2024-11-09T22:45:11.411+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:45:11.413+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:45:11.413+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:45:11.422+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:45:11.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:45:11.423+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:45:11.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-11-09T22:45:41.876+0000] {processor.py:157} INFO - Started process (PID=198) to work on /opt/airflow/dags/test.py
[2024-11-09T22:45:41.877+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:45:41.880+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:45:41.880+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:45:41.888+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:45:41.886+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:45:41.889+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:45:41.909+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-11-09T22:46:12.343+0000] {processor.py:157} INFO - Started process (PID=203) to work on /opt/airflow/dags/test.py
[2024-11-09T22:46:12.343+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:46:12.345+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:46:12.345+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:46:12.360+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:46:12.357+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:46:12.361+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:46:12.383+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.043 seconds
[2024-11-09T22:46:42.770+0000] {processor.py:157} INFO - Started process (PID=208) to work on /opt/airflow/dags/test.py
[2024-11-09T22:46:42.771+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-11-09T22:46:42.773+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:46:42.773+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-11-09T22:46:42.785+0000] {logging_mixin.py:149} INFO - [2024-11-09T22:46:42.782+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 1, in <module>
    from airflow_env import DAG
ModuleNotFoundError: No module named 'airflow_env'
[2024-11-09T22:46:42.786+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-11-09T22:46:42.805+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
